.\"     @(#)trac.1	6.4 (Berkeley) 6/27/91
.\"
.Dd September 13, 1994
.Dt TRAC 1
.Os
.Sh NAME
.Nm trac
.Nd Extremely funky macro processor.
.Sh SYNOPSIS
.Nm trac
.Sh DESCRIPTION
.Nm Trac
implements the programming language of the same name.
.Nm Trac
is a very strange language, which does everything by macro processing.
